/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    GButton: typeof import('@goose/core')['GButton']
    GPopover: typeof import('@goose/core')['GPopover']
    GSegmentedControl: typeof import('@goose/core')['GSegmentedControl']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
