/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    GButton: typeof import('./../src/components/GButton/GButton.vue')['default']
    GDrawer: typeof import('./../src/components/GDrawer/GDrawer.vue')['default']
    GPopover: typeof import('./../src/components/GPopover/GPopover.vue')['default']
    GSegmentedControl: typeof import('./../src/components/GSegmentedControl/GSegmentedControl.vue')['default']
    GSelect: typeof import('./../src/components/GSelect/GSelect.vue')['default']
    GTable: typeof import('./../src/components/GTable/GTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
