/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    GButton: typeof import('./../src/components/GButton/GButton.vue')['default']
    GDrawer: typeof import('./../src/components/GDrawer/GDrawer.vue')['default']
    GPopover: typeof import('./../src/components/GPopover/GPopover.vue')['default']
    GSegmentedControl: typeof import('./../src/components/GSegmentedControl/GSegmentedControl.vue')['default']
    GSelect: typeof import('./../src/components/GSelect/GSelect.vue')['default']
    GTable: typeof import('./../src/components/GTable/GTable.vue')['default']
    GTimeline: typeof import('./../src/components/GTimeline/GTimeline.vue')['default']
    GTimelineItem: typeof import('./../src/components/GTimeline/GTimelineItem.vue')['default']
    GTimelineLine: typeof import('./../src/components/GTimeline/GTimelineLine.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
